// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consumer/proto/event.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetEventRequest struct {
	EmpID                string   `protobuf:"bytes,1,opt,name=EmpID,proto3" json:"EmpID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Dept                 string   `protobuf:"bytes,3,opt,name=Dept,proto3" json:"Dept,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventRequest) Reset()         { *m = GetEventRequest{} }
func (m *GetEventRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventRequest) ProtoMessage()    {}
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7cd67c28e2008c7, []int{0}
}

func (m *GetEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventRequest.Unmarshal(m, b)
}
func (m *GetEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventRequest.Marshal(b, m, deterministic)
}
func (m *GetEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventRequest.Merge(m, src)
}
func (m *GetEventRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventRequest.Size(m)
}
func (m *GetEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventRequest proto.InternalMessageInfo

func (m *GetEventRequest) GetEmpID() string {
	if m != nil {
		return m.EmpID
	}
	return ""
}

func (m *GetEventRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetEventRequest) GetDept() string {
	if m != nil {
		return m.Dept
	}
	return ""
}

func (m *GetEventRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type GetEventResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventResponse) Reset()         { *m = GetEventResponse{} }
func (m *GetEventResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventResponse) ProtoMessage()    {}
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7cd67c28e2008c7, []int{1}
}

func (m *GetEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventResponse.Unmarshal(m, b)
}
func (m *GetEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventResponse.Marshal(b, m, deterministic)
}
func (m *GetEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventResponse.Merge(m, src)
}
func (m *GetEventResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventResponse.Size(m)
}
func (m *GetEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventResponse proto.InternalMessageInfo

type ListEventRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventRequest) Reset()         { *m = ListEventRequest{} }
func (m *ListEventRequest) String() string { return proto.CompactTextString(m) }
func (*ListEventRequest) ProtoMessage()    {}
func (*ListEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7cd67c28e2008c7, []int{2}
}

func (m *ListEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventRequest.Unmarshal(m, b)
}
func (m *ListEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventRequest.Marshal(b, m, deterministic)
}
func (m *ListEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventRequest.Merge(m, src)
}
func (m *ListEventRequest) XXX_Size() int {
	return xxx_messageInfo_ListEventRequest.Size(m)
}
func (m *ListEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventRequest proto.InternalMessageInfo

type ListEventResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventResponse) Reset()         { *m = ListEventResponse{} }
func (m *ListEventResponse) String() string { return proto.CompactTextString(m) }
func (*ListEventResponse) ProtoMessage()    {}
func (*ListEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7cd67c28e2008c7, []int{3}
}

func (m *ListEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventResponse.Unmarshal(m, b)
}
func (m *ListEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventResponse.Marshal(b, m, deterministic)
}
func (m *ListEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventResponse.Merge(m, src)
}
func (m *ListEventResponse) XXX_Size() int {
	return xxx_messageInfo_ListEventResponse.Size(m)
}
func (m *ListEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetEventRequest)(nil), "consumer.GetEventRequest")
	proto.RegisterType((*GetEventResponse)(nil), "consumer.GetEventResponse")
	proto.RegisterType((*ListEventRequest)(nil), "consumer.ListEventRequest")
	proto.RegisterType((*ListEventResponse)(nil), "consumer.ListEventResponse")
}

func init() { proto.RegisterFile("consumer/proto/event.proto", fileDescriptor_c7cd67c28e2008c7) }

var fileDescriptor_c7cd67c28e2008c7 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x4a, 0xfc, 0x30,
	0x10, 0xc6, 0xe9, 0xfe, 0xf7, 0x2f, 0xbb, 0xb9, 0xe8, 0x46, 0xc5, 0x1a, 0x5d, 0x95, 0x82, 0xe0,
	0xa9, 0x01, 0x15, 0x1f, 0x40, 0x76, 0x59, 0x04, 0xf1, 0xb0, 0x7a, 0xf2, 0x96, 0x86, 0xb1, 0x5b,
	0xb4, 0x49, 0x4c, 0xd2, 0x7a, 0x10, 0x2f, 0xbe, 0x82, 0x8f, 0xe6, 0x1b, 0x88, 0x0f, 0x22, 0x4d,
	0x5a, 0xdd, 0x2d, 0x3d, 0x75, 0xe6, 0xf7, 0x0d, 0xdf, 0x37, 0x19, 0x8a, 0x08, 0x97, 0xc2, 0x14,
	0x39, 0x68, 0xaa, 0xb4, 0xb4, 0x92, 0x42, 0x09, 0xc2, 0xc6, 0xae, 0xc6, 0x83, 0x46, 0x23, 0xfb,
	0xa9, 0x94, 0xe9, 0x13, 0x50, 0xa6, 0x32, 0xca, 0x84, 0x90, 0x96, 0xd9, 0x4c, 0x0a, 0xe3, 0xe7,
	0xc8, 0x41, 0xad, 0xba, 0x2e, 0x29, 0x1e, 0xe8, 0x8b, 0x66, 0x4a, 0x81, 0xae, 0xf5, 0x88, 0xa3,
	0xf5, 0x19, 0xd8, 0x69, 0xe5, 0x3c, 0x87, 0xe7, 0x02, 0x8c, 0xc5, 0x5b, 0xe8, 0xff, 0x34, 0x57,
	0x57, 0x93, 0x30, 0x38, 0x0a, 0x4e, 0x86, 0x73, 0xdf, 0x60, 0x8c, 0xfa, 0x37, 0x2c, 0x87, 0xb0,
	0xe7, 0xa0, 0xab, 0x2b, 0x36, 0x01, 0x65, 0xc3, 0x7f, 0x9e, 0x55, 0x75, 0xc5, 0xee, 0xb2, 0x1c,
	0xc2, 0xbe, 0x67, 0x55, 0x1d, 0x61, 0xb4, 0xf1, 0x17, 0x62, 0x94, 0x14, 0xc6, 0xb1, 0xeb, 0xcc,
	0xac, 0x24, 0x47, 0x9b, 0x68, 0xb4, 0xc4, 0xfc, 0xe0, 0xe9, 0x57, 0x80, 0x46, 0x8e, 0xcc, 0x40,
	0x80, 0x66, 0x56, 0xea, 0xdb, 0x92, 0xe3, 0x05, 0x1a, 0xa4, 0xb5, 0x25, 0xde, 0x8d, 0x9b, 0x63,
	0xc4, 0xad, 0xb7, 0x10, 0xd2, 0x25, 0xd5, 0x1b, 0x1c, 0xbf, 0x7f, 0x7e, 0x7f, 0xf4, 0x0e, 0xf1,
	0xd8, 0x1f, 0x36, 0x6d, 0xec, 0x7d, 0x4b, 0x5f, 0xdd, 0xbb, 0xdf, 0x30, 0x47, 0xc3, 0xdf, 0xa5,
	0xf0, 0x92, 0x5f, 0x7b, 0x7b, 0xb2, 0xd7, 0xa9, 0xd5, 0x61, 0x63, 0x17, 0xb6, 0x83, 0xb7, 0x3b,
	0xc3, 0x2e, 0x2f, 0xee, 0xcf, 0xd3, 0xcc, 0x2e, 0x8a, 0x24, 0xe6, 0x32, 0xa7, 0x4a, 0xb3, 0x12,
	0x40, 0x24, 0x8f, 0xc0, 0xdb, 0xe3, 0xab, 0xbf, 0x44, 0xb2, 0xe6, 0x3e, 0x67, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x1d, 0xf3, 0xa4, 0x92, 0x2b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EventGeneratorSvcClient is the client API for EventGeneratorSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventGeneratorSvcClient interface {
	GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error)
	ListEvent(ctx context.Context, in *ListEventRequest, opts ...grpc.CallOption) (*ListEventResponse, error)
}

type eventGeneratorSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewEventGeneratorSvcClient(cc grpc.ClientConnInterface) EventGeneratorSvcClient {
	return &eventGeneratorSvcClient{cc}
}

func (c *eventGeneratorSvcClient) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error) {
	out := new(GetEventResponse)
	err := c.cc.Invoke(ctx, "/consumer.EventGeneratorSvc/getEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventGeneratorSvcClient) ListEvent(ctx context.Context, in *ListEventRequest, opts ...grpc.CallOption) (*ListEventResponse, error) {
	out := new(ListEventResponse)
	err := c.cc.Invoke(ctx, "/consumer.EventGeneratorSvc/ListEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventGeneratorSvcServer is the server API for EventGeneratorSvc service.
type EventGeneratorSvcServer interface {
	GetEvent(context.Context, *GetEventRequest) (*GetEventResponse, error)
	ListEvent(context.Context, *ListEventRequest) (*ListEventResponse, error)
}

// UnimplementedEventGeneratorSvcServer can be embedded to have forward compatible implementations.
type UnimplementedEventGeneratorSvcServer struct {
}

func (*UnimplementedEventGeneratorSvcServer) GetEvent(ctx context.Context, req *GetEventRequest) (*GetEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvent not implemented")
}
func (*UnimplementedEventGeneratorSvcServer) ListEvent(ctx context.Context, req *ListEventRequest) (*ListEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEvent not implemented")
}

func RegisterEventGeneratorSvcServer(s *grpc.Server, srv EventGeneratorSvcServer) {
	s.RegisterService(&_EventGeneratorSvc_serviceDesc, srv)
}

func _EventGeneratorSvc_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventGeneratorSvcServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consumer.EventGeneratorSvc/GetEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventGeneratorSvcServer).GetEvent(ctx, req.(*GetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventGeneratorSvc_ListEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventGeneratorSvcServer).ListEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consumer.EventGeneratorSvc/ListEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventGeneratorSvcServer).ListEvent(ctx, req.(*ListEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventGeneratorSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "consumer.EventGeneratorSvc",
	HandlerType: (*EventGeneratorSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getEvent",
			Handler:    _EventGeneratorSvc_GetEvent_Handler,
		},
		{
			MethodName: "ListEvent",
			Handler:    _EventGeneratorSvc_ListEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consumer/proto/event.proto",
}
