apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventconsumer.fullname" . }}
  labels:
    {{- include "eventconsumer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 10000
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "eventconsumer.selectorLabels" . | nindent 4 }}
